export const APP_TAB_CHANGE = 'APP_TAB_CHANGE';

/** 単語登録 */
export const A000_UPLOAD_IMAGE = 'A000_UPLOAD_IMAGE';
export const A000_REMOVE_WORD = 'A000_REMOVE_WORD';
export const A000_REGIST_WORDS = 'A000_REGIST_WORDS';
export const A000_REGIST_SUCCESS = 'A000_REGIST_SUCCESS';
