export const ROUTE_PATH_INDEX = {
  SignIn: 1,
  Regist: 11,
  RegistList: 12,
  RegistFinish: 13,
  Study: 21,
  StudyRegist: 22,
  StudyCard: 23,
  StudyFinish: 24,
  MyPage: 31,
  Settings: 41,
  Groups: 61,
  GroupRegist: 62,
  GroupEdit: 63,
};

export const ROUTE_PATHS = {
  [ROUTE_PATH_INDEX.SignIn]: '/login',
  [ROUTE_PATH_INDEX.Regist]: '/regist',
  [ROUTE_PATH_INDEX.RegistList]: '/regist/list',
  [ROUTE_PATH_INDEX.RegistFinish]: '/regist/finish',
  [ROUTE_PATH_INDEX.MyPage]: '/mypage',
  [ROUTE_PATH_INDEX.Settings]: '/settings',
  [ROUTE_PATH_INDEX.Groups]: '/group',
  [ROUTE_PATH_INDEX.GroupRegist]: '/group/regist',
  [ROUTE_PATH_INDEX.GroupEdit]: '/group/edit',
  [ROUTE_PATH_INDEX.Study]: '/study',
  [ROUTE_PATH_INDEX.StudyRegist]: '/study/regist',
  [ROUTE_PATH_INDEX.StudyCard]: '/study/card',
  [ROUTE_PATH_INDEX.StudyFinish]: '/study/finish',
};
